name: mrrcat_flutter
description: MRRCat Flutter SDK - Unified subscription management across iOS, Android, and Web
version: 1.0.0
homepage: https://github.com/minerd/mrrcat
repository: https://github.com/minerd/mrrcat/tree/master/sdks/flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.1.13
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mrrcat.flutter
        pluginClass: MRRCatFlutterPlugin
      ios:
        pluginClass: MRRCatFlutterPlugin
